spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/local
    username: local_user
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: test